on: [push]

jobs:
  test_ubt_build_action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'Build for dev channel'
            ufbt-version: 'prerelease'
            sdk-channel: 'dev'
          - name: 'Build for release'
            ufbt-version: 'prerelease'
            sdk-channel: 'rc'

    name: "ufbt: ${{ matrix.name }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with ufbt
        uses: hedger/flipperzero-ufbt-action@dev
        id: build-app
        with:
          ufbt-version: ${{ matrix.ufbt-version }}
          sdk-channel: ${{ matrix.sdk-channel }}

      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fap-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

