name: Test ufbt action with dev SDK

on:
  [push, pull_request]

jobs:
  run-test-on-latest:
    name: Test ufbt action with dev SDK
    uses: hedger/flipperzero-ufbt-action/.github/workflows/test_ufbt.yml@dev
    with:
      ufbt-version: prerelease
      sdk-channel: dev
